"""
Summarization configuration management.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


@dataclass
class SummarizationConfig:
    """Configuration for background summarization."""
    
    # Enable/disable summarization
    enabled: bool = True
    llm_enabled: bool = True
    
    # Ollama configuration
    ollama_url: str = "http://localhost:11434"
    model: str = "qwen2.5-coder:1.5b"  # Fast, code-focused model for summarization
    
    # Rate limiting and performance
    rate_limit_seconds: float = 0.1   # Local Ollama doesn't need rate limiting
    timeout_seconds: float = 15.0     # Fail faster if something hangs
    
    # Startup timing (fallback timeout if callback system fails)
    startup_delay_seconds: float = 60.0  # Fallback timeout for summarizer startup
    
    # File size limits
    max_file_lines: int = 600
    max_file_tokens: int = 4000
    
    # LLM parameters
    temperature: float = 0.1
    max_response_tokens: int = 384    # JSON response only needs ~100-150 tokens
    
    # File filtering
    skip_patterns: List[str] = field(default_factory=lambda: [
        "**/test/**", 
        "**/*_test.*", 
        "**/vendor/**", 
        "**/node_modules/**",
        "**/__pycache__/**",
        "**/build/**",
        "**/dist/**"
    ])
    
    priority_patterns: List[str] = field(default_factory=lambda: [
        "**/src/**", 
        "**/lib/**", 
        "**/core/**"
    ])
    
    # =========================================================================
    # Phase 2 Enhancement Options
    # These control what additional context is included in LLM prompts and
    # what additional fields are requested from the LLM response.
    # =========================================================================
    
    # Include implementation signals (calls/reads/writes/subscripts) in prompt.
    # When True: Adds ~200-400 tokens to prompt with AST-extracted patterns.
    # When False: Uses simpler Phase 1 prompts, faster but less context.
    include_implementation_signals: bool = True
    
    # Request per-method summaries from LLM.
    # When True: LLM returns method_summaries dict with 1-line descriptions.
    # When False: Smaller response, faster parsing, but no method-level detail.
    include_method_summaries: bool = True
    
    # Request mechanism explanations from LLM.
    # When True: LLM explains how the code works (algorithms, caching, etc.).
    # When False: Only returns purpose/pattern/domain, no implementation detail.
    include_how_it_works: bool = True
    
    # =========================================================================
    # Simple File Detection Options
    # These control automatic detection of files that don't need LLM
    # summarization (barrel files, empty modules, generated code, etc.).
    # Simple files get template-based summaries in <1ms instead of 2-5s LLM.
    # =========================================================================
    
    # Enable automatic detection and template-based summarization of simple files.
    # When True: Barrel files, empty modules, constants-only files skip LLM.
    # When False: All files go through LLM (slower, higher token usage).
    enable_simple_file_detection: bool = True
    
    # Maximum line count for simple file consideration.
    # Files with more lines than this are never considered simple (unless
    # they match other simple patterns like Python __init__.py).
    simple_file_max_lines: int = 30
    
    # Treat all Python __init__.py files as simple barrel/re-export files.
    # When True: All __init__.py files get template summary (common case).
    # When False: Large/complex __init__.py files go through LLM.
    python_init_always_simple: bool = True
    
    # Skip LLM for files with generated code markers in header.
    # These files shouldn't be edited manually, so detailed summaries are wasteful.
    skip_generated_files: bool = True
    
    # Markers that indicate a file is auto-generated.
    # Checked against first 20 lines of file (case-insensitive).
    generated_file_markers: List[str] = field(default_factory=lambda: [
        "DO NOT EDIT",
        "@generated",
        "auto-generated",
        "Generated by",
        "This file is automatically generated"
    ])
    
    @classmethod
    def from_dict(cls, config_dict: Dict[str, Any]) -> 'SummarizationConfig':
        """Create config from dictionary."""
        # Extract summarization section
        summarization_config = config_dict.get('summarization', {})
        
        return cls(
            enabled=summarization_config.get('enabled', True),
            llm_enabled=summarization_config.get('llm_enabled', True),
            ollama_url=summarization_config.get('ollama_url', "http://localhost:11434"),
            model=summarization_config.get('model', "qwen2.5-coder:1.5b"),
            rate_limit_seconds=summarization_config.get('rate_limit_seconds', 0.1),
            timeout_seconds=summarization_config.get('timeout_seconds', 15.0),
            startup_delay_seconds=summarization_config.get('startup_delay_seconds', 30.0),
            max_file_lines=summarization_config.get('max_file_lines', 600),
            max_file_tokens=summarization_config.get('max_file_tokens', 4000),
            temperature=summarization_config.get('temperature', 0.1),
            max_response_tokens=summarization_config.get('max_response_tokens', 384),
            skip_patterns=summarization_config.get('skip_patterns', [
                "**/test/**", "**/*_test.*", "**/vendor/**", "**/node_modules/**",
                "**/__pycache__/**", "**/build/**", "**/dist/**"
            ]),
            priority_patterns=summarization_config.get('priority_patterns', [
                "**/src/**", "**/lib/**", "**/core/**"
            ]),
            # Phase 2 enhancement options
            include_implementation_signals=summarization_config.get('include_implementation_signals', True),
            include_method_summaries=summarization_config.get('include_method_summaries', True),
            include_how_it_works=summarization_config.get('include_how_it_works', True),
            # Simple file detection options
            enable_simple_file_detection=summarization_config.get('enable_simple_file_detection', True),
            simple_file_max_lines=summarization_config.get('simple_file_max_lines', 30),
            python_init_always_simple=summarization_config.get('python_init_always_simple', True),
            skip_generated_files=summarization_config.get('skip_generated_files', True),
            generated_file_markers=summarization_config.get('generated_file_markers', [
                "DO NOT EDIT", "@generated", "auto-generated",
                "Generated by", "This file is automatically generated"
            ])
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert config to dictionary."""
        return {
            'enabled': self.enabled,
            'llm_enabled': self.llm_enabled,
            'ollama_url': self.ollama_url,
            'model': self.model,
            'rate_limit_seconds': self.rate_limit_seconds,
            'timeout_seconds': self.timeout_seconds,
            'startup_delay_seconds': self.startup_delay_seconds,
            'max_file_lines': self.max_file_lines,
            'max_file_tokens': self.max_file_tokens,
            'temperature': self.temperature,
            'max_response_tokens': self.max_response_tokens,
            'skip_patterns': self.skip_patterns,
            'priority_patterns': self.priority_patterns,
            # Phase 2 enhancement options
            'include_implementation_signals': self.include_implementation_signals,
            'include_method_summaries': self.include_method_summaries,
            'include_how_it_works': self.include_how_it_works,
            # Simple file detection options
            'enable_simple_file_detection': self.enable_simple_file_detection,
            'simple_file_max_lines': self.simple_file_max_lines,
            'python_init_always_simple': self.python_init_always_simple,
            'skip_generated_files': self.skip_generated_files,
            'generated_file_markers': self.generated_file_markers
        }